#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch024_Linked_ActionAttackUnique2

#include "Basic.hpp"

#include "ABP_Ch024_Linked_ActionAttackUnique2_classes.hpp"
#include "ABP_Ch024_Linked_ActionAttackUnique2_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.Retarget
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       Retarget_0                                             (Parm, OutParm, NoDestructor)

void UABP_Ch024_Linked_ActionAttackUnique2_C::Retarget(const struct FPoseLink& InPose_0, struct FPoseLink* Retarget_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "Retarget");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_Retarget Parms{};

	Parms.InPose_0 = std::move(InPose_0);

	UObject::ProcessEvent(Func, &Parms);

	if (Retarget_0 != nullptr)
		*Retarget_0 = std::move(Parms.Retarget_0);
}


// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.ActionCustom
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       ActionCustom_0                                         (Parm, OutParm, NoDestructor)

void UABP_Ch024_Linked_ActionAttackUnique2_C::ActionCustom(const struct FPoseLink& InPose, struct FPoseLink* ActionCustom_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "ActionCustom");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_ActionCustom Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (ActionCustom_0 != nullptr)
		*ActionCustom_0 = std::move(Parms.ActionCustom_0);
}


// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.NagaraBlend
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 LowerBody                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// const struct FPoseLink&                 UpperBody                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   UpperWeights                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       NagaraBlend_0                                          (Parm, OutParm, NoDestructor)

void UABP_Ch024_Linked_ActionAttackUnique2_C::NagaraBlend(const struct FPoseLink& LowerBody, const struct FPoseLink& UpperBody, float UpperWeights, struct FPoseLink* NagaraBlend_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "NagaraBlend");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_NagaraBlend Parms{};

	Parms.LowerBody = std::move(LowerBody);
	Parms.UpperBody = std::move(UpperBody);
	Parms.UpperWeights = UpperWeights;

	UObject::ProcessEvent(Func, &Parms);

	if (NagaraBlend_0 != nullptr)
		*NagaraBlend_0 = std::move(Parms.NagaraBlend_0);
}


// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Ch024_Linked_ActionAttackUnique2_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "AnimGraph");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Ch024_Linked_ActionAttackUnique2_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "BlueprintUpdateAnimation");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Ch024_Linked_ActionAttackUnique2.ABP_Ch024_Linked_ActionAttackUnique2_C.ExecuteUbergraph_ABP_Ch024_Linked_ActionAttackUnique2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Ch024_Linked_ActionAttackUnique2_C::ExecuteUbergraph_ABP_Ch024_Linked_ActionAttackUnique2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Ch024_Linked_ActionAttackUnique2_C", "ExecuteUbergraph_ABP_Ch024_Linked_ActionAttackUnique2");

	Params::ABP_Ch024_Linked_ActionAttackUnique2_C_ExecuteUbergraph_ABP_Ch024_Linked_ActionAttackUnique2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
