#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Variation

#include "Basic.hpp"

#include "ABP_Ch000_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Variation.ABP_Variation_C
// 0x0000 (0x3490 - 0x3490)
class UABP_Variation_C final : public UABP_Ch000_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Variation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Variation_C")
	}
	static class UABP_Variation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Variation_C>();
	}
};

SDK_NAMESPACE_END
