#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch046_Unique2AimLinked

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Ch046_Unique2AimLinked.ABP_Ch046_Unique2AimLinked_C
// 0x0810 (0x0AD0 - 0x02C0)
class UABP_Ch046_Unique2AimLinked_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x02C8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x02F8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x0410(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x0440(0x0118)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x0558(0x0190)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x06E8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x0718(0x0118)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x0830(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0948(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0978(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0A90(0x0030)()
	float                                         Pitch;                                             // 0x0AC0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC4[0x4];                                      // 0x0AC4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  Owner;                                             // 0x0AC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActionCustom(const struct FPoseLink& InPose, struct FPoseLink* ActionCustom_0);
	void NagaraBlend(const struct FPoseLink& LowerBody, const struct FPoseLink& UpperBody, float UpperWeights, struct FPoseLink* NagaraBlend_0);
	void Retarget(const struct FPoseLink& InPose_0, struct FPoseLink* Retarget_0);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void SetIKEffectorOffset(float Offset);
	void SetIKBlend(float BlendAlpha);
	void SetHandScaleInfo(float handScale, float leftHandBlendAlpha, float rightHandBlendAlpha, bool bIsExpanding);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void SetAimingOffset(class ACharacterBattle* char_0);
	void ExecuteUbergraph_ABP_Ch046_Unique2AimLinked(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Ch046_Unique2AimLinked_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Ch046_Unique2AimLinked_C")
	}
	static class UABP_Ch046_Unique2AimLinked_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Ch046_Unique2AimLinked_C>();
	}
};

SDK_NAMESPACE_END
