#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Ch046_Extra_Linked

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Ch046_Extra_Linked.ABP_Ch046_Extra_Linked_C
// 0x32A0 (0x3560 - 0x02C0)
class UABP_Ch046_Extra_Linked_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x02C8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x02F8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x0410(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x0440(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x0558(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x0588(0x0118)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x06A0(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_33;                         // 0x06C0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_32;                         // 0x07B0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_31;                         // 0x08A0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_30;                         // 0x0990(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_29;                         // 0x0A80(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_28;                         // 0x0B70(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_27;                         // 0x0C60(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_26;                         // 0x0D50(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_25;                         // 0x0E40(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_24;                         // 0x0F30(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_23;                         // 0x1020(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_22;                         // 0x1110(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_21;                         // 0x1200(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_20;                         // 0x12F0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_19;                         // 0x13E0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_18;                         // 0x14D0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_17;                         // 0x15C0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_16;                         // 0x16B0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_15;                         // 0x17A0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_14;                         // 0x1890(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_13;                         // 0x1980(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_12;                         // 0x1A70(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_11;                         // 0x1B60(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_10;                         // 0x1C50(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_9;                          // 0x1D40(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_8;                          // 0x1E30(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_7;                          // 0x1F20(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_6;                          // 0x2010(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_5;                          // 0x2100(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_4;                          // 0x21F0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_3;                          // 0x22E0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_2;                          // 0x23D0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_1;                          // 0x24C0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone;                            // 0x25B0(0x00F0)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x26A0(0x0190)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_9;                        // 0x2830(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_8;                        // 0x2938(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_7;                        // 0x2A40(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x2B48(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x2C50(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x2D58(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x2E60(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x2F68(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x3070(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x3178(0x0108)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x3280(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x32A0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x32D0(0x0118)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x33E8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x3500(0x0030)()
	float                                         CurrentHandScale;                                  // 0x3530(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         leftHandBlendAlpha;                                // 0x3534(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         rightHandBlendAlpha;                               // 0x3538(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InHandScale;                                       // 0x353C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InterpSpeed;                                       // 0x3540(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                InverseBodyScale;                                  // 0x3544(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BodyScale;                                         // 0x3550(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HandPitch;                                         // 0x3554(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Retarget(const struct FPoseLink& InPose_0, struct FPoseLink* Retarget_0);
	void ActionCustom(const struct FPoseLink& InPose, struct FPoseLink* ActionCustom_0);
	void NagaraBlend(const struct FPoseLink& LowerBody, const struct FPoseLink& UpperBody, float UpperWeights, struct FPoseLink* NagaraBlend_0);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void SetAimingOffset(class ACharacterBattle* char_0);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Ch046_Extra_Linked_AnimGraphNode_ModifyBone_50171FE74B43862CED2137B8B1BF7967();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Ch046_Extra_Linked_AnimGraphNode_ModifyBone_FF7FDB0E4DBD375ADBAC24BDBA464A17();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void SetIKEffectorOffset(float Offset);
	void SetIKBlend(float BlendAlpha);
	void SetHandScaleInfo(float handScale, float leftHandBlendAlpha_0, float rightHandBlendAlpha_0, bool bIsExpanding);
	void BlueprintLinkedAnimationLayersInitialized();
	void ExecuteUbergraph_ABP_Ch046_Extra_Linked(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Ch046_Extra_Linked_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Ch046_Extra_Linked_C")
	}
	static class UABP_Ch046_Extra_Linked_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Ch046_Extra_Linked_C>();
	}
};

SDK_NAMESPACE_END
