#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Agones

#include "Basic.hpp"

#include "Agones_classes.hpp"
#include "Agones_parameters.hpp"


namespace SDK
{

// Function Agones.AgonesSubsystem.Get
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const class UObject*                    WorldContext                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UAgonesSubsystem*                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UAgonesSubsystem* UAgonesSubsystem::Get(const class UObject* WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("AgonesSubsystem", "Get");

	Params::AgonesSubsystem_Get Parms{};

	Parms.WorldContext = WorldContext;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function Agones.AgonesSubsystem.AddListValue
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FList& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::AddListValue(const class FString& Key, const class FString& value, TDelegate<void(const struct FList& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "AddListValue");

	Params::AgonesSubsystem_AddListValue Parms{};

	Parms.Key = std::move(Key);
	Parms.value = std::move(value);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Allocate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::Allocate(TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Allocate");

	Params::AgonesSubsystem_Allocate Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Connect
// (Final, Native, Public, BlueprintCallable)

void UAgonesSubsystem::Connect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Connect");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.ConnectSuccess
// (Final, Native, Private)
// Parameters:
// const struct FGameServerResponse&       GameServerResponse                                     (Parm, NativeAccessSpecifierPublic)

void UAgonesSubsystem::ConnectSuccess(const struct FGameServerResponse& GameServerResponse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "ConnectSuccess");

	Params::AgonesSubsystem_ConnectSuccess Parms{};

	Parms.GameServerResponse = std::move(GameServerResponse);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.DecrementCounter
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   amount                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::DecrementCounter(const class FString& Key, int64 amount, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "DecrementCounter");

	Params::AgonesSubsystem_DecrementCounter Parms{};

	Parms.Key = std::move(Key);
	Parms.amount = amount;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GameServer
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FGameServerResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GameServer(TDelegate<void(const struct FGameServerResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GameServer");

	Params::AgonesSubsystem_GameServer Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GetConnectedPlayers
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FConnectedPlayersResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GetConnectedPlayers(TDelegate<void(const struct FConnectedPlayersResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GetConnectedPlayers");

	Params::AgonesSubsystem_GetConnectedPlayers Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GetCounter
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FCounterResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GetCounter(const class FString& Key, TDelegate<void(const struct FCounterResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GetCounter");

	Params::AgonesSubsystem_GetCounter Parms{};

	Parms.Key = std::move(Key);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GetList
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FList& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GetList(const class FString& Key, TDelegate<void(const struct FList& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GetList");

	Params::AgonesSubsystem_GetList Parms{};

	Parms.Key = std::move(Key);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GetPlayerCapacity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FCountResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GetPlayerCapacity(TDelegate<void(const struct FCountResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GetPlayerCapacity");

	Params::AgonesSubsystem_GetPlayerCapacity Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.GetPlayerCount
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FCountResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::GetPlayerCount(TDelegate<void(const struct FCountResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "GetPlayerCount");

	Params::AgonesSubsystem_GetPlayerCount Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Health
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::Health(TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Health");

	Params::AgonesSubsystem_Health Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.HealthPing
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   RateSeconds                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAgonesSubsystem::HealthPing(float RateSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "HealthPing");

	Params::AgonesSubsystem_HealthPing Parms{};

	Parms.RateSeconds = RateSeconds;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.IncrementCounter
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   amount                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::IncrementCounter(const class FString& Key, int64 amount, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "IncrementCounter");

	Params::AgonesSubsystem_IncrementCounter Parms{};

	Parms.Key = std::move(Key);
	Parms.amount = amount;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.IsPlayerConnected
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    playerId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FConnectedResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::IsPlayerConnected(const class FString& playerId, TDelegate<void(const struct FConnectedResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "IsPlayerConnected");

	Params::AgonesSubsystem_IsPlayerConnected Parms{};

	Parms.playerId = std::move(playerId);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.PlayerConnect
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    playerId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FConnectedResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::PlayerConnect(const class FString& playerId, TDelegate<void(const struct FConnectedResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "PlayerConnect");

	Params::AgonesSubsystem_PlayerConnect Parms{};

	Parms.playerId = std::move(playerId);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.PlayerDisconnect
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    playerId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FDisconnectResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::PlayerDisconnect(const class FString& playerId, TDelegate<void(const struct FDisconnectResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "PlayerDisconnect");

	Params::AgonesSubsystem_PlayerDisconnect Parms{};

	Parms.playerId = std::move(playerId);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Ready
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::Ready(TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Ready");

	Params::AgonesSubsystem_Ready Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.RemoveListValue
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FList& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::RemoveListValue(const class FString& Key, const class FString& value, TDelegate<void(const struct FList& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "RemoveListValue");

	Params::AgonesSubsystem_RemoveListValue Parms{};

	Parms.Key = std::move(Key);
	Parms.value = std::move(value);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Reserve
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int64                                   Seconds                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::Reserve(int64 Seconds, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Reserve");

	Params::AgonesSubsystem_Reserve Parms{};

	Parms.Seconds = Seconds;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.SetAnnotation
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::SetAnnotation(const class FString& Key, const class FString& value, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "SetAnnotation");

	Params::AgonesSubsystem_SetAnnotation Parms{};

	Parms.Key = std::move(Key);
	Parms.value = std::move(value);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.SetCounterCapacity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   Capacity                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::SetCounterCapacity(const class FString& Key, int64 Capacity, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "SetCounterCapacity");

	Params::AgonesSubsystem_SetCounterCapacity Parms{};

	Parms.Key = std::move(Key);
	Parms.Capacity = Capacity;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.SetCounterCount
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   count                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::SetCounterCount(const class FString& Key, int64 count, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "SetCounterCount");

	Params::AgonesSubsystem_SetCounterCount Parms{};

	Parms.Key = std::move(Key);
	Parms.count = count;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.SetLabel
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::SetLabel(const class FString& Key, const class FString& value, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "SetLabel");

	Params::AgonesSubsystem_SetLabel Parms{};

	Parms.Key = std::move(Key);
	Parms.value = std::move(value);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.SetPlayerCapacity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int64                                   count                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::SetPlayerCapacity(int64 count, TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "SetPlayerCapacity");

	Params::AgonesSubsystem_SetPlayerCapacity Parms{};

	Parms.count = count;
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.Shutdown
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FEmptyResponse& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::Shutdown(TDelegate<void(const struct FEmptyResponse& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "Shutdown");

	Params::AgonesSubsystem_Shutdown Parms{};

	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.UpdateList
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    Key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FList&                     List                                                   (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FList& Response)>SuccessDelegate                                        (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
// TDelegate<void(const struct FAgonesError& Error)>ErrorDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::UpdateList(const class FString& Key, const struct FList& List, TDelegate<void(const struct FList& Response)> SuccessDelegate, TDelegate<void(const struct FAgonesError& Error)> ErrorDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "UpdateList");

	Params::AgonesSubsystem_UpdateList Parms{};

	Parms.Key = std::move(Key);
	Parms.List = std::move(List);
	Parms.SuccessDelegate = SuccessDelegate;
	Parms.ErrorDelegate = ErrorDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Agones.AgonesSubsystem.WatchGameServer
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TDelegate<void(const struct FGameServerResponse& Response)>WatchDelegate                                          (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UAgonesSubsystem::WatchGameServer(TDelegate<void(const struct FGameServerResponse& Response)> WatchDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AgonesSubsystem", "WatchGameServer");

	Params::AgonesSubsystem_WatchGameServer Parms{};

	Parms.WatchDelegate = WatchDelegate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

