#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AirForceDecal_L3_0

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Ch012_AirForceDecal_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass AirForceDecal_L3.AirForceDecal_L3_C
// 0x0008 (0x02F0 - 0x02E8)
class AirForceDecal_L3_0::AAirForceDecal_L3_C final : public ACh012_AirForceDecal_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_AirForceDecal_L3_C;                 // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_AirForceDecal_L3(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass AirForceDecal_L3.AirForceDecal_L3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AirForceDecal_L3_C")
	}
	static class AirForceDecal_L3_0::AAirForceDecal_L3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AirForceDecal_L3_0::AAirForceDecal_L3_C>();
	}
};

SDK_NAMESPACE_END
