#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionSPJumpPadRise

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "GameModule_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionSPJumpPadRise.BP_ActionSPJumpPadRise_C
// 0x0018 (0x0290 - 0x0278)
class UBP_ActionSPJumpPadRise_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                JumpPadNormal;                                     // 0x0280(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionSPJumpPadRise(int32 EntryPoint);
	void BP_ActionMain();
	void UpdateCo_Routine();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnBeginAction(const class FName& prevAction);
	void CalcSpeedH(float* Initial_Speed, float* Last_Speed, float* Accel_Span);
	void CalcJumpParam(float* Speed, float* span);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionSPJumpPadRise_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionSPJumpPadRise_C")
	}
	static class UBP_ActionSPJumpPadRise_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionSPJumpPadRise_C>();
	}
};
DUMPER7_ASSERTS_UBP_ActionSPJumpPadRise_C;

}

