#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AbilitySupplyBeta

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AbilitySupplyBeta.BP_AbilitySupplyBeta_C
// 0x0010 (0x0440 - 0x0430)
class ABP_AbilitySupplyBeta_C final : public AAbilityActor
{
public:
	class USphereComponent*                       Sphere;                                            // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_It000_Card;                                     // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AbilitySupplyBeta_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AbilitySupplyBeta_C")
	}
	static class ABP_AbilitySupplyBeta_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AbilitySupplyBeta_C>();
	}
};

SDK_NAMESPACE_END
