#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionPlusUltra

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionPlusUltra.BP_ActionPlusUltra_C
// 0x0018 (0x0288 - 0x0270)
class UBP_ActionPlusUltra_C final : public UActionPlusUltra
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          isAction;                                          // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          isResetPoint;                                      // 0x0279(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_27A[0x2];                                      // 0x027A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         plusUltraMaxTime;                                  // 0x027C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isCall;                                            // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x3];                                      // 0x0281(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         responseTimer;                                     // 0x0284(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionPlusUltra(int32 EntryPoint);
	void ForceEndAction();
	void ClientRecieveActionMain();
	void BP_OnRecieveActionPing(int32 ping);
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_OnAnimNotify(const class FName& Type, const class FName& Event);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_ActionRemote();
	void BroadcastRollSlotUniqueSkill();
	void BroadcastRollSlotUniqueSkill_OnBegin();
	bool IsPlusUltraCancelled(class FName nextAction);
	void ClearGrabbed();
	void ResetBuffCondition();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionPlusUltra_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionPlusUltra_C")
	}
	static class UBP_ActionPlusUltra_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionPlusUltra_C>();
	}
};

SDK_NAMESPACE_END
