#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDamageGrabbed

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionDamageGrabbed.BP_ActionDamageGrabbed_C
// 0x0008 (0x0278 - 0x0270)
class UBP_ActionDamageGrabbed_C final : public UActionDamageGrabbed
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionDamageGrabbed(int32 EntryPoint);
	void BP_OnLeaveGroundEvent();
	void BP_ActionRemote();
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionDamageGrabbed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionDamageGrabbed_C")
	}
	static class UBP_ActionDamageGrabbed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionDamageGrabbed_C>();
	}
};

SDK_NAMESPACE_END
