#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionHover

#include "Basic.hpp"

#include "GameModule_structs.hpp"
#include "CommonModule_structs.hpp"
#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionHover.BP_ActionHover_C
// 0x0018 (0x0290 - 0x0278)
class UBP_ActionHover_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         totalDelta;                                        // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         deltaMultipli;                                     // 0x0284(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         upDownSpeedMultipli;                               // 0x0288(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MinFallSpeed;                                      // 0x028C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionHover(int32 EntryPoint);
	void BP_OnBeginCondition(ECharacterConditionId ID, int32 Level, float value, class APlayerStateBattle* instigatedPlayer);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnLandingEvent();
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void InitMovement();
	void MainMovement();
	void UpdateMoveDirection();
	void UpdateCharacterDirection();
	void UpdateMoveSpeed();
	void UpdateLocation();

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionHover_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionHover_C")
	}
	static class UBP_ActionHover_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionHover_C>();
	}
};

SDK_NAMESPACE_END
