#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionJumpBeginForward

#include "Basic.hpp"

#include "GameModule_structs.hpp"
#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionJumpBeginForward.BP_ActionJumpBeginForward_C
// 0x0010 (0x0288 - 0x0278)
class UBP_ActionJumpBeginForward_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         HoldTime;                                          // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionJumpBeginForward(int32 EntryPoint);
	void HighJumpBegin();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionJumpBeginForward_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionJumpBeginForward_C")
	}
	static class UBP_ActionJumpBeginForward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionJumpBeginForward_C>();
	}
};

SDK_NAMESPACE_END
