#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDodge

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionDodge.BP_ActionDodge_C
// 0x0008 (0x0278 - 0x0270)
class UBP_ActionDodge_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionDodge(int32 EntryPoint);
	void BP_OnBeginAction(const class FName& prevAction);
	void SpeedControl();
	void BP_ActionMain();
	void BP_OnEndAction(const class FName& nextAction);
	void TurnInitial();
	void SetSpeed();
	void ClearSpeed();
	void UpdateDirection();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionDodge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionDodge_C")
	}
	static class UBP_ActionDodge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionDodge_C>();
	}
};

SDK_NAMESPACE_END
