#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionJumpFall

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionJumpFall.BP_ActionJumpFall_C
// 0x0010 (0x0280 - 0x0270)
class UBP_ActionJumpFall_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         BlendInTime;                                       // 0x0278(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionJumpFall(int32 EntryPoint);
	void BP_OnLandingEvent();
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void UpdateCo_Routine();
	void BP_OnEndAction(const class FName& nextAction);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionJumpFall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionJumpFall_C")
	}
	static class UBP_ActionJumpFall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionJumpFall_C>();
	}
};

SDK_NAMESPACE_END
