#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDamageStrongCarryFront

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionDamageStrongCarryFront.BP_ActionDamageStrongCarryFront_C
// 0x0008 (0x02C0 - 0x02B8)
class UBP_ActionDamageStrongCarryFront_C final : public UActionDamageStrongCarryFront
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionDamageStrongCarryFront(int32 EntryPoint);
	void BP_ActionRemote();
	void BP_OnLandingEvent();
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();
	void DecideAnimationId(EAnimationId* AnimationId);
	float GetCharacterBattleZ();
	float GetCharacterBattleTime();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionDamageStrongCarryFront_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionDamageStrongCarryFront_C")
	}
	static class UBP_ActionDamageStrongCarryFront_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionDamageStrongCarryFront_C>();
	}
};

SDK_NAMESPACE_END
