#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch025V2_U2_Param

#include "Basic.hpp"

#include "BP_Ch025V2_U2_Param_classes.hpp"
#include "BP_Ch025V2_U2_Param_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Ch025V2_U2_Param.BP_Ch025V2_U2_Param_C.GetUnique2Param
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FFCh025V2_U2_Param*              paramData_0                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch025V2_U2_Param_C::GetUnique2Param(struct FFCh025V2_U2_Param* paramData_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch025V2_U2_Param_C", "GetUnique2Param");

	Params::BP_Ch025V2_U2_Param_C_GetUnique2Param Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (paramData_0 != nullptr)
		*paramData_0 = std::move(Parms.paramData_0);
}


// Function BP_Ch025V2_U2_Param.BP_Ch025V2_U2_Param_C.GetUnique2MagazineParamData
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// int32                                   uniqueLevel                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bShockWave                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  Rate                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch025V2_U2_Param_C::GetUnique2MagazineParamData(int32 uniqueLevel, bool bShockWave, float* Rate) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch025V2_U2_Param_C", "GetUnique2MagazineParamData");

	Params::BP_Ch025V2_U2_Param_C_GetUnique2MagazineParamData Parms{};

	Parms.uniqueLevel = uniqueLevel;
	Parms.bShockWave = bShockWave;

	UObject::ProcessEvent(Func, &Parms);

	if (Rate != nullptr)
		*Rate = Parms.Rate;
}


// Function BP_Ch025V2_U2_Param.BP_Ch025V2_U2_Param_C.GetUnique2CameraParam
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FFCh025V2_U2_CameraParam*        CameraParam_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch025V2_U2_Param_C::GetUnique2CameraParam(struct FFCh025V2_U2_CameraParam* CameraParam_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch025V2_U2_Param_C", "GetUnique2CameraParam");

	Params::BP_Ch025V2_U2_Param_C_GetUnique2CameraParam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CameraParam_0 != nullptr)
		*CameraParam_0 = std::move(Parms.CameraParam_0);
}


SDK_NAMESPACE_END
