#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch202_ActionAttack_Melee

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch202_ActionAttack_Melee.BP_Ch202_ActionAttack_Melee_C
// 0x0030 (0x0520 - 0x04F0)
class UBP_Ch202_ActionAttack_Melee_C final : public UCh202ActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         hitCount;                                          // 0x04F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAttackHit;                                        // 0x04FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4FD[0x3];                                      // 0x04FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacterBattle*                       HitChara;                                          // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<bool>                                  bLevelUpFlag;                                      // 0x0508(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bEnableNotifyA;                                    // 0x0518(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bEnableJumpBeginAirAttack;                         // 0x0519(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_Ch202_ActionAttack_Melee(int32 EntryPoint);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_OnLandingGround();
	void BP_OnLeaveGroundEvent();
	void BP_OnHitAttackEvent(const struct FVector& HitLocation, class FName projectileName, class FName damageParamName, class ACharacterBattle* hitCharacter, float damageValue);
	void BP_OnLandingAir();
	void BP_ActionMain();
	void BP_OnChangeAttackPhaseGroundForRemote(int32 nextPhase);
	void BP_OnChangeAttackPhaseGround(int32 nextPhase);
	void BP_OnBeginActionAttackGround(const class FName& prevAction);
	void SetChaseAir();
	void BP_OnChangeAttackPhaseAirForRemote(int32 nextPhase);
	void BP_OnChangeAttackPhaseAir(int32 nextPhase);
	void BP_OnBeginActionAttackAir(const class FName& prevAction);
	void AD_EV_A();
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void GetMoveDirection(struct FVector* MoveDirection);
	void InitAttack(bool findTarget);
	void MeleeFinishEvent(class ACharacterBattle* damageChara, int32 Index_0);
	void Brake_Transition_By_AttackAction();
	void Clear_Level_Up_Flag();
	void GetChaseSpeedA(float* Speed);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch202_ActionAttack_Melee_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch202_ActionAttack_Melee_C")
	}
	static class UBP_Ch202_ActionAttack_Melee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch202_ActionAttack_Melee_C>();
	}
};

SDK_NAMESPACE_END
