#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_RollSlot_Ability_Heal

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CC_RollSlot_Ability_Heal.BP_CC_RollSlot_Ability_Heal_C.ExecuteUbergraph_BP_CC_RollSlot_Ability_Heal
// 0x0020 (0x0020 - 0x0000)
struct BP_CC_RollSlot_Ability_Heal_C_ExecuteUbergraph_BP_CC_RollSlot_Ability_Heal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_value;                                // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharacterBattle*                       CallFunc_BP_GetOwnerCharacterBattle_ReturnValue;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCharacterConditionControlComponent*    CallFunc_BP_GetConditionControlComponent_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_IsValidCondition_ReturnValue;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_CC_RollSlot_Ability_Heal_C_ExecuteUbergraph_BP_CC_RollSlot_Ability_Heal;

// Function BP_CC_RollSlot_Ability_Heal.BP_CC_RollSlot_Ability_Heal_C.BP_OnUpdateIntervalValue
// 0x0004 (0x0004 - 0x0000)
struct BP_CC_RollSlot_Ability_Heal_C_BP_OnUpdateIntervalValue final
{
public:
	float                                         value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CC_RollSlot_Ability_Heal_C_BP_OnUpdateIntervalValue;

}

