#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_Dying

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CC_Dying.BP_CC_Dying_C.ExecuteUbergraph_BP_CC_Dying
// 0x0008 (0x0008 - 0x0000)
struct BP_CC_Dying_C_ExecuteUbergraph_BP_CC_Dying final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_value;                                // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CC_Dying_C_ExecuteUbergraph_BP_CC_Dying;

// Function BP_CC_Dying.BP_CC_Dying_C.BP_OnUpdateIntervalValue
// 0x0004 (0x0004 - 0x0000)
struct BP_CC_Dying_C_BP_OnUpdateIntervalValue final
{
public:
	float                                         value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CC_Dying_C_BP_OnUpdateIntervalValue;

}

