#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch006_ActionAttack_Unique1

#include "Basic.hpp"

#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CommonModule_structs.hpp"
#include "GameModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch006_ActionAttack_Unique1.BP_Ch006_ActionAttack_Unique1_C
// 0x0048 (0x04E8 - 0x04A0)
class UBP_Ch006_ActionAttack_Unique1_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         BlendOnTIme;                                       // 0x04A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BlendOffTIme;                                      // 0x04AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bBlendOff;                                         // 0x04B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B1[0x3];                                      // 0x04B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                SlingDirection;                                    // 0x04B4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHitAttackAir;                                    // 0x04C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C1[0x3];                                      // 0x04C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         limitTimer;                                        // 0x04C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         moveSpeed;                                         // 0x04C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         speedRate;                                         // 0x04CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BASE_SPEED;                                        // 0x04D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                HitLocation;                                       // 0x04D4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAttackEnd;                                       // 0x04E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsBeginAir;                                        // 0x04E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void InitializeTargetLocation();
	void SetTargetLocation(const struct FVector& InLocation);
	void CalcRotator(const struct FTransform& BaseTransform, const struct FVector& targetLocation, struct FRotator* ret);
	void BP_OnBeginActionAttackAir(const class FName& prevAction);
	void BP_OnChangeAttackPhaseAir(int32 nextPhase);
	void BP_ActionAttackMainAir();
	void BP_OnEndActionAttackAir(const class FName& nextAction);
	void BP_OnChangeAttackPhaseAirForRemote(int32 nextPhase);
	void SlideAdjust();
	void BP_OnHitProjectileEvent(EAttackId projectileAttackId, EAttackHitResult Type, const struct FVector& Location, class AActor* hitActor);
	void MoveForward();
	void BP_OnBeginActionAttackGround(const class FName& prevAction);
	void BP_ActionAttackMainGround();
	void BP_OnChangeAttackPhaseGround(int32 nextPhase);
	void BP_OnChangeAttackPhaseGroundForRemote(int32 nextPhase);
	void BP_OnEndActionAttackGround(const class FName& nextAction);
	void BP_OnAngleRangeOutGround();
	void TongueControl();
	void BlendOn();
	void BlendOff(float span);
	void TongueControl_Grab(class ACharacterBattle* hitCharacter);
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnLoadParams(const class FName& ActionName, int32 uniqueLevel);
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void BP_OnBeginAimingMode();
	void BP_OnEndAimingMode();
	void SetActiveTongueBones(bool IsActive);
	void BP_ActionRemote();
	void PostSpawnProjectileBullet(class ABullet* spawnedBullet);
	void PostSpawnProjectileBulletForRemote(class ABullet* spawnedBullet);
	void ExecuteUbergraph_BP_Ch006_ActionAttack_Unique1(int32 EntryPoint);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch006_ActionAttack_Unique1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch006_ActionAttack_Unique1_C")
	}
	static class UBP_Ch006_ActionAttack_Unique1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch006_ActionAttack_Unique1_C>();
	}
};

SDK_NAMESPACE_END
