#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch001_ActionAttack_Special

#include "Basic.hpp"

#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch001_ActionAttack_Special.BP_Ch001_ActionAttack_Special_C
// 0x0010 (0x04C8 - 0x04B8)
class UBP_Ch001_ActionAttack_Special_C final : public UActionAttack_Special_Coop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bPiggyBackNow;                                     // 0x04C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsMagazineEmpty;                                   // 0x04C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Turning(float* Turn_Span);
	void Initialize();
	void BP_ActionMain();
	void Piggyback_End();
	void Piggyback_Move();
	void Piggyback_Begin();
	void BP_ActionRemote();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnAbortGrabEvent();
	void BP_OnEmptyMagazine();
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void BP_OnBeginCondition(ECharacterConditionId ID, int32 Level, float value, class APlayerStateBattle* instigatedPlayer);
	void ExecuteUbergraph_BP_Ch001_ActionAttack_Special(int32 EntryPoint);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch001_ActionAttack_Special_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch001_ActionAttack_Special_C")
	}
	static class UBP_Ch001_ActionAttack_Special_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch001_ActionAttack_Special_C>();
	}
};

SDK_NAMESPACE_END
