#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_Orb_Penalty

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CC_Orb_Penalty.BP_CC_Orb_Penalty_C
// 0x0008 (0x0158 - 0x0150)
class UBP_CC_Orb_Penalty_C final : public UCharacterConditionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0150(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_CC_Orb_Penalty(int32 EntryPoint);
	void BP_OnEndCondition();
	void BP_OnBeginCondition();
	void BP_OnUpdateIntervalValue(float value);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CC_Orb_Penalty_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CC_Orb_Penalty_C")
	}
	static class UBP_CC_Orb_Penalty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CC_Orb_Penalty_C>();
	}
};
DUMPER7_ASSERTS_UBP_CC_Orb_Penalty_C;

}

