#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch017_ActionAttack_Unique2

#include "Basic.hpp"

#include "BP_Ch017_ActionAttack_Unique2_classes.hpp"
#include "BP_Ch017_ActionAttack_Unique2_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.ExecuteUbergraph_BP_Ch017_ActionAttack_Unique2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::ExecuteUbergraph_BP_Ch017_ActionAttack_Unique2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "ExecuteUbergraph_BP_Ch017_ActionAttack_Unique2");

	Params::BP_Ch017_ActionAttack_Unique2_C_ExecuteUbergraph_BP_Ch017_ActionAttack_Unique2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnLoadParamsForChargeAttack
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      ActionName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   uniqueLevel                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnLoadParamsForChargeAttack(const class FName& ActionName, int32 uniqueLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnLoadParamsForChargeAttack");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnLoadParamsForChargeAttack Parms{};

	Parms.ActionName = ActionName;
	Parms.uniqueLevel = uniqueLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnEndAimingMode
// (Event, Protected, BlueprintEvent)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnEndAimingMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnEndAimingMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginAimingMode
// (Event, Protected, BlueprintEvent)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginAimingMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginAimingMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginActionAttackChargeAir
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginActionAttackChargeAir(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginActionAttackChargeAir");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnBeginActionAttackChargeAir Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginActionAttackAir
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginActionAttackAir(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginActionAttackAir");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnBeginActionAttackAir Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginActionAttackChargeGround
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginActionAttackChargeGround(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginActionAttackChargeGround");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnBeginActionAttackChargeGround Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginActionAttackGround
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginActionAttackGround(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginActionAttackGround");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnBeginActionAttackGround Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnEndActionAttackCharge
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnEndActionAttackCharge(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnEndActionAttackCharge");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnEndActionAttackCharge Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_ActionAttackChargeMain
// (Event, Protected, BlueprintEvent)

void UBP_Ch017_ActionAttack_Unique2_C::BP_ActionAttackChargeMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_ActionAttackChargeMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_Ch017_ActionAttack_Unique2_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnLoadParams
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      ActionName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   uniqueLevel                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnLoadParams(const class FName& ActionName, int32 uniqueLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnLoadParams");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnLoadParams Parms{};

	Parms.ActionName = ActionName;
	Parms.uniqueLevel = uniqueLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnEndAction");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch017_ActionAttack_Unique2_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_OnBeginAction");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch017_ActionAttack_Unique2.BP_Ch017_ActionAttack_Unique2_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_Ch017_ActionAttack_Unique2_C::BP_IsEnableShiftAction(const class FName& nextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch017_ActionAttack_Unique2_C", "BP_IsEnableShiftAction");

	Params::BP_Ch017_ActionAttack_Unique2_C_BP_IsEnableShiftAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
