#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch103_ActionAttack_Unique3

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"
#include "CommonModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch103_ActionAttack_Unique3.BP_Ch103_ActionAttack_Unique3_C
// 0x0088 (0x0528 - 0x04A0)
class UBP_Ch103_ActionAttack_Unique3_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          IsHit;                                             // 0x04A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A9[0x3];                                      // 0x04A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CurrentHitPrevTime;                                // 0x04AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharacterBattle*                       hitCharacter;                                      // 0x04B0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                HitLocation;                                       // 0x04B8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C4[0x4];                                      // 0x04C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCustomParticleSystemComponent*         InPotalParticle;                                   // 0x04C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCustomParticleSystemComponent*         OutPotalParticle;                                  // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                SpawnInGateLocation;                               // 0x04D8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               SpawnInGateRotation;                               // 0x04E4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                targetLocation;                                    // 0x04F0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               TargetRotation;                                    // 0x04FC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsAnimationLoopEnd;                               // 0x0508(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsSuperArmor;                                     // 0x0509(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bLastPushGround;                                   // 0x050A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bLastPushAir;                                      // 0x050B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bEndControlBullet;                                 // 0x050C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_50D[0x3];                                      // 0x050D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HoldTimeCounter;                                   // 0x0510(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bNowWarp;                                          // 0x0514(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bWarpFlag;                                         // 0x0515(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bEndFlag;                                          // 0x0516(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bBeforeHold;                                       // 0x0517(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         ShotSpanCounter;                                   // 0x0518(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BetaHoldTime;                                      // 0x051C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bBetaShot;                                         // 0x0520(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_521[0x3];                                      // 0x0521(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BetaShotWaitCount;                                 // 0x0524(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Beta_Shot();
	void AlphaShot();
	void Get_Warp_Magazine_Shoot_by_Rate(float* WarpMagazineShootByRate);
	void Get_Beta_Magazine_Shoot_By_Rate(float* BetaMagazineShootByRate);
	void Get_Alpha_Magazine_Shoot_by_Rate(float* AlphaMagazineShootByRate);
	void SetEnableAvatarHand(bool condition);
	void GetInGatePaticle(class UParticleSystem** InGate, class UParticleSystem** DeactivateInGate);
	void SetEnableMaterial(bool flag);
	void SpawnOutGate();
	void DeactivateInGate();
	void Spawn_in_Gate();
	void SetEffectVisiblity(bool Visiblity);
	void ClearHand();
	void Set_Hand();
	void Initialize();
	void BP_OnHitAttackEventAir(const struct FVector& HitLocation_0, class FName projectileName, class FName damageParamName, class ACharacterBattle* hitCharacter_0);
	void BP_OnChangeAttackPhaseAirForRemote(int32 nextPhase);
	void BP_OnChangeAttackPhaseAir(int32 nextPhase);
	void BP_OnBeginActionAttackAir(const class FName& prevAction);
	void CustomEvent(EBulletDestroyType Type, const class FName projectileName);
	void BP_OnChangeAttackPhaseGround(int32 nextPhase);
	void BP_OnHitAttackEventGround(const struct FVector& HitLocation_0, class FName projectileName, class FName damageParamName, class ACharacterBattle* hitCharacter_0);
	void BP_OnChangeAttackPhaseGroundForRemote(int32 nextPhase);
	void BP_OnBeginActionAttackGround(const class FName& prevAction);
	void BP_OnDestroyedProjectileEvent(EBulletDestroyType Type, const class FName projectileName);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void BP_RegisterAttackAction_Avatar();
	void BP_UnRegisterAttackAction_Avatar();
	void BP_OnLoadParams(const class FName& ActionName, int32 uniqueLevel);
	void OnClearHand();
	void OnSetHand();
	void OnSetHand_Avatar();
	void OnClearHand_Avatar();
	void BP_OnBootDamage(bool bSuperArmor, bool bZeroDamage, const struct FDamageInfo& DamageInfo, const struct FDamageParam& DamageParam);
	void BP_OnHitProjectileEvent(EAttackId projectileAttackId, EAttackHitResult Type, const struct FVector& Location, class AActor* hitActor);
	void ExecuteUbergraph_BP_Ch103_ActionAttack_Unique3(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch103_ActionAttack_Unique3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch103_ActionAttack_Unique3_C")
	}
	static class UBP_Ch103_ActionAttack_Unique3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch103_ActionAttack_Unique3_C>();
	}
};

SDK_NAMESPACE_END
