#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch007_ActionAttack_Unique2

#include "Basic.hpp"

#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"
#include "CommonModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch007_ActionAttack_Unique2.BP_Ch007_ActionAttack_Unique2_C
// 0x0010 (0x04B0 - 0x04A0)
class UBP_Ch007_ActionAttack_Unique2_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          IsShot;                                            // 0x04A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsGround;                                          // 0x04A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4AA[0x2];                                      // 0x04AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LoadFoolTime;                                      // 0x04AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void LoadParam();
	void Ch007TextureChange(bool bChange);
	void BP_OnBeginActionAttackAir(const class FName& prevAction);
	void BP_OnChangeAttackPhaseAir(int32 nextPhase);
	void BP_OnChangeAttackPhaseAirForRemote(int32 nextPhase);
	void BP_ActionAttackMainAir();
	void BP_ActionAttackRemoteAir();
	void BP_OnBeginActionAttackGround(const class FName& prevAction);
	void BP_OnChangeAttackPhaseGround(int32 nextPhase);
	void BP_OnChangeAttackPhaseGroundForRemote(int32 nextPhase);
	void BP_ActionAttackMainGround();
	void BP_ActionAttackRemoteGround();
	void BP_OnLoadParams(const class FName& ActionName, int32 uniqueLevel);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void CustomEventAttackClient(int32 nextPhase);
	void CustomEventAttackRemote(int32 nextPhase);
	void ExecuteUbergraph_BP_Ch007_ActionAttack_Unique2(int32 EntryPoint);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch007_ActionAttack_Unique2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch007_ActionAttack_Unique2_C")
	}
	static class UBP_Ch007_ActionAttack_Unique2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch007_ActionAttack_Unique2_C>();
	}
};

SDK_NAMESPACE_END
