#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch100_ActionAttack_Unique3

#include "Basic.hpp"

#include "InGameModule_structs.hpp"
#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "CommonModule_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ch100_ActionAttack_Unique3.BP_Ch100_ActionAttack_Unique3_C
// 0x0018 (0x04B8 - 0x04A0)
class UBP_Ch100_ActionAttack_Unique3_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         LoopTime;                                          // 0x04A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         loadLoopTime;                                      // 0x04AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LoadLoopTime_Giant;                                // 0x04B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnBeginActionAttackAir(const class FName& prevAction);
	void BP_OnChangeAttackPhaseAir(int32 nextPhase);
	void BP_OnChangeAttackPhaseAirForRemote(int32 nextPhase);
	void BP_OnChangeAttackPhaseGround(int32 nextPhase);
	void BP_OnChangeAttackPhaseGroundForRemote(int32 nextPhase);
	void BP_OnBeginActionAttackGround(const class FName& prevAction);
	void BP_OnLoadParams(const class FName& ActionName, int32 uniqueLevel);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();
	void BP_ActionRemote();
	void BP_OnLandingAir();
	void BP_OnLandingGround();
	void BP_OnLeaveGroundEvent();
	void BP_OnNotificationAttackDedicatedEvent(EAttackDedicatedEventId ID);
	void BP_OnHitAttackEvent(const struct FVector& HitLocation, class FName projectileName, class FName damageParamName, class ACharacterBattle* hitCharacter, float damageValue);
	void Cancel_Check();
	void ExecuteUbergraph_BP_Ch100_ActionAttack_Unique3(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ch100_ActionAttack_Unique3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ch100_ActionAttack_Unique3_C")
	}
	static class UBP_Ch100_ActionAttack_Unique3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ch100_ActionAttack_Unique3_C>();
	}
};

SDK_NAMESPACE_END
