#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerControllerInGame

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_PlayerControllerInGame.BP_PlayerControllerInGame_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerControllerInGame_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerControllerInGame.BP_PlayerControllerInGame_C.ExecuteUbergraph_BP_PlayerControllerInGame
// 0x0008 (0x0008 - 0x0000)
struct BP_PlayerControllerInGame_C_ExecuteUbergraph_BP_PlayerControllerInGame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocalPlayerController_ReturnValue;      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocalPlayerController_ReturnValue_1;    // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
