#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_St04_02_kitchen

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_St04_02_kitchen.BP_St04_02_kitchen_C
// 0x0040 (0x0408 - 0x03C8)
class ABP_St04_02_kitchen_C final : public ABgProp
{
public:
	class UStaticMeshComponent*                   SM_St04_02_Chair01B6;                              // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Desk01B;                                // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_04_02_kitchen;                                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Chair01B5;                              // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Chair01B4;                              // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Chair01B3;                              // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Chair01B2;                              // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_St04_02_Chair01B1;                              // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_St04_02_kitchen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_St04_02_kitchen_C")
	}
	static class ABP_St04_02_kitchen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_St04_02_kitchen_C>();
	}
};

SDK_NAMESPACE_END
