#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_St_Ambulance01B_1

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_St_Ambulance01B_1.BP_St_Ambulance01B_1_C
// 0x0008 (0x03D0 - 0x03C8)
class ABP_St_Ambulance01B_1_C final : public ABgProp
{
public:
	class UStaticMeshComponent*                   SM_St_Ambulance01A;                                // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_St_Ambulance01B_1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_St_Ambulance01B_1_C")
	}
	static class ABP_St_Ambulance01B_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_St_Ambulance01B_1_C>();
	}
};

SDK_NAMESPACE_END
