#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_st04_15_Water01A

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "BackendSubsystem_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_st04_15_Water01A.BP_st04_15_Water01A_C
// 0x0010 (0x03D8 - 0x03C8)
class ABP_st04_15_Water01A_C final : public ABgProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBgLayoutSquareComponent*               SM_st01_07_Water01A_TEST;                          // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnLoaded_73E253044E21990AFE596481930FD870(class UObject* Loaded);
	void OnLoaded_DE9604474326E1FBEA4CA7959189909A(class UObject* Loaded);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_st04_15_Water01A(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_st04_15_Water01A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_st04_15_Water01A_C")
	}
	static class ABP_st04_15_Water01A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_st04_15_Water01A_C>();
	}
};

SDK_NAMESPACE_END
