#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SupplyBox

#include "Basic.hpp"

#include "BP_SupplyBox_classes.hpp"
#include "BP_SupplyBox_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SupplyBox.BP_SupplyBox_C.ExecuteUbergraph_BP_SupplyBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SupplyBox_C::ExecuteUbergraph_BP_SupplyBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "ExecuteUbergraph_BP_SupplyBox");

	Params::BP_SupplyBox_C_ExecuteUbergraph_BP_SupplyBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SupplyBox.BP_SupplyBox_C.OnDestroyStaging
// (Event, Protected, BlueprintEvent)

void ABP_SupplyBox_C::OnDestroyStaging()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "OnDestroyStaging");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.OnStatusChangedDelegate_Event
// (BlueprintCallable, BlueprintEvent)

void ABP_SupplyBox_C::OnStatusChangedDelegate_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "OnStatusChangedDelegate_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SupplyBox_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.タイムライン_0__UpdateFunc
// (BlueprintEvent)

void ABP_SupplyBox_C::タイムライン_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "タイムライン_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.タイムライン_0__FinishedFunc
// (BlueprintEvent)

void ABP_SupplyBox_C::タイムライン_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "タイムライン_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_SupplyBox_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SupplyBox.BP_SupplyBox_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_SupplyBox_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SupplyBox_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
