#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Su016

#include "Basic.hpp"

#include "BP_Su016_classes.hpp"
#include "BP_Su016_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Su016.BP_Su016_C.ExecuteUbergraph_BP_Su016
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Su016_C::ExecuteUbergraph_BP_Su016(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Su016_C", "ExecuteUbergraph_BP_Su016");

	Params::BP_Su016_C_ExecuteUbergraph_BP_Su016 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Su016.BP_Su016_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Su016_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Su016_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Su016.BP_Su016_C.SetParentRotator
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Su016_C::SetParentRotator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Su016_C", "SetParentRotator");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
