#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_Unique2_Child_1

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPB_Unique2_Child.BPB_Unique2_Child_C
// 0x0020 (0x1D40 - 0x1D20)
class BPB_Unique2_Child_1::ABPB_Unique2_Child_C : public ACh012Unique2Child
{
public:
	class UBattleCustomParticleSystemComponent*   smokeParticle;                                     // 0x1D20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHeroCapsuleComponent*                  h1;                                                // 0x1D28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHeroSphereComponent*                   b1;                                                // 0x1D30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BPB_Unique2_Child.BPB_Unique2_Child_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPB_Unique2_Child_C")
	}
	static class BPB_Unique2_Child_1::ABPB_Unique2_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BPB_Unique2_Child_1::ABPB_Unique2_Child_C>();
	}
};

SDK_NAMESPACE_END
