#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_ThunderBackGroundHit

#include "Basic.hpp"

#include "InGameModule_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPB_ThunderBackGroundHit.BPB_ThunderBackGroundHit_C
// 0x0020 (0x1D20 - 0x1D00)
class ABPB_ThunderBackGroundHit_C final : public ACh007BackGroundHit
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHeroSphereComponent*                   h1;                                                // 0x1D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBattleCustomParticleSystemComponent*   BattleCustomParticleSystem;                        // 0x1D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ExecuteUbergraph_BPB_ThunderBackGroundHit(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPB_ThunderBackGroundHit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPB_ThunderBackGroundHit_C")
	}
	static class ABPB_ThunderBackGroundHit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPB_ThunderBackGroundHit_C>();
	}
};

SDK_NAMESPACE_END
