#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_Unique2_Child_0

#include "Basic.hpp"

#include "BPB_Unique2_Child_0_classes.hpp"
#include "BPB_Unique2_Child_0_parameters.hpp"


SDK_NAMESPACE_START

// Function BPB_Unique2_Child.BPB_Unique2_Child_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void BPB_Unique2_Child_0::ABPB_Unique2_Child_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_Unique2_Child_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
