#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_Unique1_5

#include "Basic.hpp"

#include "BPB_Unique1_5_classes.hpp"
#include "BPB_Unique1_5_parameters.hpp"


SDK_NAMESPACE_START

// Function BPB_Unique1.BPB_Unique1_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void BPB_Unique1_5::ABPB_Unique1_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_Unique1_C", "ReceiveTick");

	Params::BPB_Unique1_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPB_Unique1.BPB_Unique1_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void BPB_Unique1_5::ABPB_Unique1_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_Unique1_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPB_Unique1.BPB_Unique1_C.ExecuteUbergraph_BPB_Unique1
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void BPB_Unique1_5::ABPB_Unique1_C::ExecuteUbergraph_BPB_Unique1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPB_Unique1_C", "ExecuteUbergraph_BPB_Unique1");

	Params::BPB_Unique1_C_ExecuteUbergraph_BPB_Unique1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
