#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_Unique1_Child

#include "Basic.hpp"

#include "BPG_Unique1_Child_classes.hpp"
#include "BPG_Unique1_Child_parameters.hpp"


SDK_NAMESPACE_START

// Function BPG_Unique1_Child.BPG_Unique1_Child_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void BPG_Unique1_Child::ABPG_Unique1_Child_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_Unique1_Child_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPG_Unique1_Child.BPG_Unique1_Child_C.ExecuteUbergraph_BPG_Unique1_Child
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void BPG_Unique1_Child::ABPG_Unique1_Child_C::ExecuteUbergraph_BPG_Unique1_Child(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_Unique1_Child_C", "ExecuteUbergraph_BPG_Unique1_Child");

	Params::BPG_Unique1_Child_C_ExecuteUbergraph_BPG_Unique1_Child Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
