#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_Ch046_Unique1_Base

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPG_Ch046_Unique1_Base.BPG_Ch046_Unique1_Base_C
// 0x0010 (0x0510 - 0x0500)
class ABPG_Ch046_Unique1_Base_C : public ACh046Unique1Gen
{
public:
	class UBattleCustomParticleSystemComponent*   BattleCustomParticleSystem;                        // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPG_Ch046_Unique1_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPG_Ch046_Unique1_Base_C")
	}
	static class ABPG_Ch046_Unique1_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPG_Ch046_Unique1_Base_C>();
	}
};

SDK_NAMESPACE_END
