#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_Ch046_Unique1_Level1

#include "Basic.hpp"

#include "BPG_Ch046_Unique1_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPG_Ch046_Unique1_Level1.BPG_Ch046_Unique1_Level1_C
// 0x0000 (0x0510 - 0x0510)
class ABPG_Ch046_Unique1_Level1_C final : public ABPG_Ch046_Unique1_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPG_Ch046_Unique1_Level1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPG_Ch046_Unique1_Level1_C")
	}
	static class ABPG_Ch046_Unique1_Level1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPG_Ch046_Unique1_Level1_C>();
	}
};

SDK_NAMESPACE_END
