#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPG_Ch006_Unique1Gen

#include "Basic.hpp"

#include "BPG_Ch006_Unique1Gen_classes.hpp"
#include "BPG_Ch006_Unique1Gen_parameters.hpp"


SDK_NAMESPACE_START

// Function BPG_Ch006_Unique1Gen.BPG_Ch006_Unique1Gen_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPG_Ch006_Unique1Gen_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_Ch006_Unique1Gen_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPG_Ch006_Unique1Gen.BPG_Ch006_Unique1Gen_C.ExecuteUbergraph_BPG_Ch006_Unique1Gen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPG_Ch006_Unique1Gen_C::ExecuteUbergraph_BPG_Ch006_Unique1Gen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_Ch006_Unique1Gen_C", "ExecuteUbergraph_BPG_Ch006_Unique1Gen");

	Params::BPG_Ch006_Unique1Gen_C_ExecuteUbergraph_BPG_Ch006_Unique1Gen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPG_Ch006_Unique1Gen.BPG_Ch006_Unique1Gen_C.BP_DecideJsonIndex
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 ABPG_Ch006_Unique1Gen_C::BP_DecideJsonIndex() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPG_Ch006_Unique1Gen_C", "BP_DecideJsonIndex");

	Params::BPG_Ch006_Unique1Gen_C_BP_DecideJsonIndex Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
