#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_CaptureFinish

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTT_CaptureFinish.BTT_CaptureFinish_C
// 0x0008 (0x00B0 - 0x00A8)
class UBTT_CaptureFinish_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BTT_CaptureFinish(int32 EntryPoint);
	void ReceiveAbortAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTT_CaptureFinish_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTT_CaptureFinish_C")
	}
	static class UBTT_CaptureFinish_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_CaptureFinish_C>();
	}
};

SDK_NAMESPACE_END
