#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Preloader

#include "Basic.hpp"


SDK_NAMESPACE_START

// ScriptStruct Preloader.PreloadInfo
// 0x0030 (0x0030 - 0x0000)
struct alignas(0x08) FPreloadInfo final
{
public:
	uint8                                         Pad_0[0x30];                                       // 0x0000(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

SDK_NAMESPACE_END
