#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_GashaOfferRatio

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SL_GashaOfferRatio.SL_GashaOfferRatio_C
// 0x0000 (0x0228 - 0x0228)
class ASL_GashaOfferRatio_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SL_GashaOfferRatio_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SL_GashaOfferRatio_C")
	}
	static class ASL_GashaOfferRatio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASL_GashaOfferRatio_C>();
	}
};
DUMPER7_ASSERTS_ASL_GashaOfferRatio_C;

SDK_NAMESPACE_END
