#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FinisherActionGuideWidget

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FinisherActionGuideWidget.WBP_FinisherActionGuideWidget_C
// 0x0008 (0x0310 - 0x0308)
class UWBP_FinisherActionGuideWidget_C final : public UCharacterActionGuideWidget
{
public:
	class UImage*                                 Image;                                             // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FinisherActionGuideWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FinisherActionGuideWidget_C")
	}
	static class UWBP_FinisherActionGuideWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FinisherActionGuideWidget_C>();
	}
};

SDK_NAMESPACE_END
