#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GashaHistory_listItemTimer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GashaHistory_listItemTimer.WBP_GashaHistory_listItemTimer_C
// 0x0018 (0x0420 - 0x0408)
class UWBP_GashaHistory_listItemTimer_C final : public UTimeWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image;                                             // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_2;                                       // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_GashaHistory_listItemTimer(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GashaHistory_listItemTimer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GashaHistory_listItemTimer_C")
	}
	static class UWBP_GashaHistory_listItemTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GashaHistory_listItemTimer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GashaHistory_listItemTimer_C;

SDK_NAMESPACE_END
