#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizePanel_MyAd

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomizePanel_MyAd.WBP_CustomizePanel_MyAd_C
// 0x0010 (0x0598 - 0x0588)
class UWBP_CustomizePanel_MyAd_C final : public UCustomizePanelWidget
{
public:
	class UNamedSlot*                             ImageNamedSlot;                                    // 0x0588(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Clipping_C*                        WBP_Clipping;                                      // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomizePanel_MyAd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomizePanel_MyAd_C")
	}
	static class UWBP_CustomizePanel_MyAd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomizePanel_MyAd_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CustomizePanel_MyAd_C;

SDK_NAMESPACE_END
