#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ProfileRank

#include "Basic.hpp"

#include "GameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ProfileRank.WBP_ProfileRank_C
// 0x0000 (0x0380 - 0x0380)
class UWBP_ProfileRank_C final : public UProfileDisplayRankWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ProfileRank_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ProfileRank_C")
	}
	static class UWBP_ProfileRank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ProfileRank_C>();
	}
};

SDK_NAMESPACE_END
