#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MyRoom_SendLikeItem

#include "Basic.hpp"

#include "WBP_MyRoom_SendLikeItem_classes.hpp"
#include "WBP_MyRoom_SendLikeItem_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MyRoom_SendLikeItem.WBP_MyRoom_SendLikeItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MyRoom_SendLikeItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MyRoom_SendLikeItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MyRoom_SendLikeItem.WBP_MyRoom_SendLikeItem_C.ExecuteUbergraph_WBP_MyRoom_SendLikeItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MyRoom_SendLikeItem_C::ExecuteUbergraph_WBP_MyRoom_SendLikeItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MyRoom_SendLikeItem_C", "ExecuteUbergraph_WBP_MyRoom_SendLikeItem");

	Params::WBP_MyRoom_SendLikeItem_C_ExecuteUbergraph_WBP_MyRoom_SendLikeItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
