#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Contact_Notice

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Contact_Notice.WBP_Contact_Notice_C
// 0x0000 (0x04D0 - 0x04D0)
class UWBP_Contact_Notice_C final : public UContactNoticeWidget
{
public:
	class UWidget* DoCustomNavigation_Right(EUINavigation Navigation_0);
	class UWidget* DoCustomNavigation_left(EUINavigation Navigation_0);
	void UpdateList();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Contact_Notice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Contact_Notice_C")
	}
	static class UWBP_Contact_Notice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Contact_Notice_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Contact_Notice_C;

SDK_NAMESPACE_END
