#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomMatchDetail_EditButton

#include "Basic.hpp"

#include "GameModule_classes.hpp"
#include "Engine_structs.hpp"
#include "UIFramework_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomMatchDetail_EditButton.WBP_CustomMatchDetail_EditButton_C
// 0x0040 (0x0810 - 0x07D0)
class UWBP_CustomMatchDetail_EditButton_C final : public UCheckButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UProgressBar*                           bgBody;                                            // 0x07D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_FocusAnimationListItem_C*          FocusWidget;                                       // 0x07E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x07E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_6;                                           // 0x07F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_95;                                          // 0x07F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_207;                                         // 0x0800(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdjustText_C*                      WBP_AdjustText;                                    // 0x0808(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CustomMatchDetail_EditButton(int32 EntryPoint);
	void focus(class UAppWidget* Widget, EWidgetInputType inputType);
	void Decide(class UAppWidget* Widget, EWidgetInputType inputType);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomMatchDetail_EditButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomMatchDetail_EditButton_C")
	}
	static class UWBP_CustomMatchDetail_EditButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomMatchDetail_EditButton_C>();
	}
};

SDK_NAMESPACE_END
