#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FriendListItem_Button

#include "Basic.hpp"

#include "WBP_FriendListItem_Button_classes.hpp"
#include "WBP_FriendListItem_Button_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_FriendListItem_Button.WBP_FriendListItem_Button_C.ExecuteUbergraph_WBP_FriendListItem_Button
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FriendListItem_Button_C::ExecuteUbergraph_WBP_FriendListItem_Button(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendListItem_Button_C", "ExecuteUbergraph_WBP_FriendListItem_Button");

	Params::WBP_FriendListItem_Button_C_ExecuteUbergraph_WBP_FriendListItem_Button Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FriendListItem_Button.WBP_FriendListItem_Button_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_FriendListItem_Button_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendListItem_Button_C", "PreConstruct");

	Params::WBP_FriendListItem_Button_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
