#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PastItemReceiveCautionWindow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UIFramework_structs.hpp"
#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PastItemReceiveCautionWindow.WBP_PastItemReceiveCautionWindow_C
// 0x0010 (0x0380 - 0x0370)
class UWBP_PastItemReceiveCautionWindow_C final : public UWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_GeneralWindowFrame_C*              WBP_GeneralWindowFrame;                            // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PastItemReceiveCautionWindow(int32 EntryPoint);
	void Construct();
	void BndEvt__WBP_PastItemReceiveCautionWindow_WBP_GeneralWindowFrame_K2Node_ComponentBoundEvent_2_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_PastItemReceiveCautionWindow_WBP_GeneralWindowFrame_K2Node_ComponentBoundEvent_1_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_PastItemReceiveCautionWindow_WBP_GeneralWindowFrame_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void OnDecideDelegate_イベント_0(class UAppWidget* Widget, EWidgetInputType inputType);
	void OnLeftDecideDelegate(class UAppWidget* Widget, EWidgetInputType inputType);
	void Open();
	void Close();
	void GetRightButton(class UWidgetButton** rightButton);
	void GetLeftButton(class UWidgetButton** leftButton);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PastItemReceiveCautionWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PastItemReceiveCautionWindow_C")
	}
	static class UWBP_PastItemReceiveCautionWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PastItemReceiveCautionWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PastItemReceiveCautionWindow_C;

SDK_NAMESPACE_END
