#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Gasha_OfferRatio

#include "Basic.hpp"

#include "WBP_Gasha_OfferRatio_classes.hpp"
#include "WBP_Gasha_OfferRatio_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.ExecuteUbergraph_WBP_Gasha_OfferRatio
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::ExecuteUbergraph_WBP_Gasha_OfferRatio(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "ExecuteUbergraph_WBP_Gasha_OfferRatio");

	Params::WBP_Gasha_OfferRatio_C_ExecuteUbergraph_WBP_Gasha_OfferRatio Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_L_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_L_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_L_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature");

	Params::WBP_Gasha_OfferRatio_C_BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_L_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_R_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_R_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_R_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature");

	Params::WBP_Gasha_OfferRatio_C_BndEvt__WBP_Gasha_OfferRatio_WBP_WindowButton_R_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_0_OnOutsideButtonDownEventDelegate__DelegateSignature
// (BlueprintEvent)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_0_OnOutsideButtonDownEventDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_0_OnOutsideButtonDownEventDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature");

	Params::WBP_Gasha_OfferRatio_C_BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio__tabWidget_K2Node_ComponentBoundEvent_3_OnSwitchTabEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   newSelectTab                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio__tabWidget_K2Node_ComponentBoundEvent_3_OnSwitchTabEventDelegate__DelegateSignature(int32 newSelectTab)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio__tabWidget_K2Node_ComponentBoundEvent_3_OnSwitchTabEventDelegate__DelegateSignature");

	Params::WBP_Gasha_OfferRatio_C_BndEvt__WBP_Gasha_OfferRatio__tabWidget_K2Node_ComponentBoundEvent_3_OnSwitchTabEventDelegate__DelegateSignature Parms{};

	Parms.newSelectTab = newSelectTab;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_2_OnWindowEventDelegate__DelegateSignature
// (BlueprintEvent)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_2_OnWindowEventDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_EmptyWindow_K2Node_ComponentBoundEvent_2_OnWindowEventDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Gasha_OfferRatio_C::BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature");

	Params::WBP_Gasha_OfferRatio_C_BndEvt__WBP_Gasha_OfferRatio_WBP_ReturnButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Gasha_OfferRatio_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.OnAnalogValueChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FAnalogInputEvent&         InAnalogInputEvent                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Gasha_OfferRatio_C::OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "OnAnalogValueChanged");

	Params::WBP_Gasha_OfferRatio_C_OnAnalogValueChanged Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InAnalogInputEvent = std::move(InAnalogInputEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Gasha_OfferRatio.WBP_Gasha_OfferRatio_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Gasha_OfferRatio_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Gasha_OfferRatio_C", "OnKeyDown");

	Params::WBP_Gasha_OfferRatio_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
