#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PackList

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PackList.WBP_PackList_C
// 0x0008 (0x0390 - 0x0388)
class UWBP_PackList_C final : public UPackItemListWidget
{
public:
	class UImage*                                 backImage;                                         // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AddScrollOffset(const struct FAnalogInputEvent& InAnalogEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PackList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PackList_C")
	}
	static class UWBP_PackList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PackList_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PackList_C;

SDK_NAMESPACE_END
