#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StaffRollBgMovie

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_StaffRollBgMovie.WBP_StaffRollBgMovie_C
// 0x0010 (0x0380 - 0x0370)
class UWBP_StaffRollBgMovie_C final : public UWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_0;                                           // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_StaffRollBgMovie(int32 EntryPoint);
	void OnInitialized();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_StaffRollBgMovie_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_StaffRollBgMovie_C")
	}
	static class UWBP_StaffRollBgMovie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_StaffRollBgMovie_C>();
	}
};
DUMPER7_ASSERTS_UWBP_StaffRollBgMovie_C;

SDK_NAMESPACE_END
