#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Setting_Observer

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"
#include "OutGameModule_structs.hpp"
#include "OutGameModule_classes.hpp"
#include "InputCore_structs.hpp"
#include "UIFramework_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Setting_Observer.WBP_Setting_Observer_C
// 0x0280 (0x0868 - 0x05E8)
class UWBP_Setting_Observer_C final : public UObserverSettingWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Begin;                                             // 0x05F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _accelerate;                                       // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _aimingPlayer;                                     // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _beforePosition;                                   // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _changeBeforeView;                                 // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _changeNextView;                                   // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _changeTeamBeforeView;                             // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _changeTeamNextView;                               // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _descent;                                          // 0x0630(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdjustText_C*                      _gemePadText;                                      // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdjustText_C*                      _keyboardText;                                     // 0x0640(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             _keyboardTipsText;                                 // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             _list;                                             // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_WindowButton_C*                    _menuButton;                                       // 0x0658(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             _menuTipsText;                                     // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _moveDown;                                         // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _moveLeft;                                         // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _moveRight;                                        // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _nearPlayer;                                       // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _observerMap;                                      // 0x0688(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _playerListView;                                   // 0x0690(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             _playSettinglist;                                  // 0x0698(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _rise;                                             // 0x06A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _showPlayerStatus;                                 // 0x06A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _slowDown;                                         // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Keyboard_C*         _teleportOnMap;                                    // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              A;                                                 // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              B;                                                 // 0x06C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 balloon;                                           // 0x06D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 balloon_1;                                         // 0x06D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 hatsume;                                           // 0x06E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 hatsume_1;                                         // 0x06E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x06F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              l1;                                                // 0x06F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              L3;                                                // 0x0700(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 listBG_bottom;                                     // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 listBG_bottom_1;                                   // 0x0710(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 listBG_up;                                         // 0x0718(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 listBG_up_1;                                       // 0x0720(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              Options;                                           // 0x0728(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 padBG;                                             // 0x0730(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              PadDown;                                           // 0x0738(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              PadLeft;                                           // 0x0740(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              PadRight;                                          // 0x0748(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              PadUP;                                             // 0x0750(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              R1;                                                // 0x0758(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              R2;                                                // 0x0760(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              R3;                                                // 0x0768(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              TouchPadLeft;                                      // 0x0770(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              TouchPadRight;                                     // 0x0778(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdjustText_C*                      WBP_AdjustText;                                    // 0x0780(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdjustText_C*                      WBP_AdjustText_112;                                // 0x0788(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              X;                                                 // 0x0790(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Button_Key_C*              Y;                                                 // 0x0798(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 selectindex)> CloseKeyConfigPopup;                           // 0x07A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(EKeyConfigCommandListType listType, EKeyConfigurableCommand curCommand)> OpenKeyConfigPopup; // 0x07B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UWBP_Setting_Button_Key_C*              Temp;                                              // 0x07C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<EKeyConfigurableCommand, struct FKey>    OnCommandList;                                     // 0x07C8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	EKeyConfigurableCommand                       prevTempCommand;                                   // 0x0818(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_819[0x7];                                      // 0x0819(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              FocusSaveButton;                                   // 0x0820(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              FocusResetButton;                                  // 0x0830(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          NewVar_0;                                          // 0x0840(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_841[0x7];                                      // 0x0841(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_Setting_Button_Key_C*>      PadButtonArray;                                    // 0x0848(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UWBP_Setting_Button_Keyboard_C*> KeyboardButtonArray;                               // 0x0858(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void ExecuteUbergraph_WBP_Setting_Observer(int32 EntryPoint);
	void BndEvt__WBP_Setting_Observer__menuButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_WBP_WindowButton_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BP_GameKeyboardButtonOptionDataSetting();
	void CheckSwap(EKeyConfigurableCommand prevCommand, EKeyConfigurableCommand nextCommand);
	void BP_GamePadButtonOptionDataSetting();
	void TargetSettingCommand(int32 selectindex);
	void BndEvt__WBP_Setting_KeyConfig_A_K2Node_ComponentBoundEvent_23_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_B_K2Node_ComponentBoundEvent_22_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_X_K2Node_ComponentBoundEvent_21_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_Y_K2Node_ComponentBoundEvent_20_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R2_K2Node_ComponentBoundEvent_19_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R1_K2Node_ComponentBoundEvent_18_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L3_K2Node_ComponentBoundEvent_17_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R3_K2Node_ComponentBoundEvent_16_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_TouchPad_K2Node_ComponentBoundEvent_15_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_Option_K2Node_ComponentBoundEvent_14_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_OptionLong_K2Node_ComponentBoundEvent_13_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadDown_K2Node_ComponentBoundEvent_8_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadRight_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadLeft_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadUP_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L2_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L1_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void BndEvt__WBP_Setting_KeyConfig_Y_K2Node_ComponentBoundEvent_34_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_Y_K2Node_ComponentBoundEvent_33_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_X_K2Node_ComponentBoundEvent_32_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_X_K2Node_ComponentBoundEvent_31_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_TouchPad_K2Node_ComponentBoundEvent_30_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_TouchPad_K2Node_ComponentBoundEvent_29_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R3_K2Node_ComponentBoundEvent_28_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R3_K2Node_ComponentBoundEvent_27_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R2_K2Node_ComponentBoundEvent_26_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R2_K2Node_ComponentBoundEvent_25_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R1_K2Node_ComponentBoundEvent_23_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_R1_K2Node_ComponentBoundEvent_22_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadUP_K2Node_ComponentBoundEvent_21_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadUP_K2Node_ComponentBoundEvent_20_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadRight_K2Node_ComponentBoundEvent_19_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadRight_K2Node_ComponentBoundEvent_18_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadLeft_K2Node_ComponentBoundEvent_17_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadDown_K2Node_ComponentBoundEvent_16_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadDown_K2Node_ComponentBoundEvent_15_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_OptionLong_K2Node_ComponentBoundEvent_14_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_OptionLong_K2Node_ComponentBoundEvent_12_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_Option_K2Node_ComponentBoundEvent_11_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_Option_K2Node_ComponentBoundEvent_10_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L3_K2Node_ComponentBoundEvent_9_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L3_K2Node_ComponentBoundEvent_8_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L2_K2Node_ComponentBoundEvent_7_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L2_K2Node_ComponentBoundEvent_6_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L1_K2Node_ComponentBoundEvent_5_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_B_K2Node_ComponentBoundEvent_4_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_B_K2Node_ComponentBoundEvent_3_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_A_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_A_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_PadLeft_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_Setting_KeyConfig_L1_K2Node_ComponentBoundEvent_24_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void OpenCommandList(class UAppWidget* Target);
	void CreatePadButtonArray();
	void CreateKeyboardButtonArray();
	void ChangeCommand(EKeyConfigurableCommand prevCommand, EKeyConfigurableCommand nextCommand);
	class UWidget* DoCustomR1Navigation(EUINavigation Navigation_0);
	class UWidget* DoCustomL1Navigation(EUINavigation Navigation_0);
	void GetCommandList(EKeyConfigCommandListType KeyType, TArray<EKeyConfigurableCommand>* commandList);
	void ChangeKey(const struct FKey& prevKey, const struct FKey& nextKey);
	class UWidget* DoCustomSaveButtonFocusNavigation(EUINavigation Navigation_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Setting_Observer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Setting_Observer_C")
	}
	static class UWBP_Setting_Observer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_Observer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Setting_Observer_C;

SDK_NAMESPACE_END
