#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TrainingMenuOutGame

#include "Basic.hpp"

#include "CommonModule_structs.hpp"
#include "Engine_structs.hpp"
#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TrainingMenuOutGame.WBP_TrainingMenuOutGame_C
// 0x0020 (0x0438 - 0x0418)
class UWBP_TrainingMenuOutGame_C final : public UTrainingMenuOutGameWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USafeZone*                              SafeZone_0;                                        // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ChatButton_C*                      WBP_ChatButton;                                    // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_TrainingMenu_C*                    WBP_TrainingMenu;                                  // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_TrainingMenuOutGame(int32 EntryPoint);
	void OnInitialized();
	void BndEvt__WBP_TrainingMenuOutGame_WBP_TrainingMenu_K2Node_ComponentBoundEvent_1_OnCloseDelegate__DelegateSignature();
	void BndEvt__WBP_TrainingMenuOutGame_WBP_TrainingMenu_K2Node_ComponentBoundEvent_0_OnDecideDelegate__DelegateSignature();
	void OnGetAiCharacter(int32 Index_0, ECharacterId* characterId, int32* defUnique1Level, int32* defUnique2Level, int32* defUnique3Level, int32* skillVariationCode, int32* aiActionIndex);
	void OnGetPlayerCharacter(ECharacterId* characterId, int32* defUnique1Level, int32* defUnique2Level, int32* defUnique3Level, int32* skillVariationCode);
	void OnGetSetting(int32* damageTypeIndex, bool* bFriendlyFire);
	void OnGetSetting2(bool* bFastReload);
	void OnSetAiCharacter(int32 Index_0, ECharacterId characterId, int32 defUnique1Level, int32 defUnique2Level, int32 defUnique3Level, int32 skillVariationCode, int32 aiActionIndex);
	void OnSetPlayerCharacter(ECharacterId characterId, int32 defUnique1Level, int32 defUnique2Level, int32 defUnique3Level, int32 skillVariationCode);
	void OnSetSetting(int32 damageTypeIndex, bool bFriendlyFire);
	void OnSetSetting2(bool bFastReload);
	void OnSetLeaderMode(bool bLeader);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TrainingMenuOutGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TrainingMenuOutGame_C")
	}
	static class UWBP_TrainingMenuOutGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TrainingMenuOutGame_C>();
	}
};

SDK_NAMESPACE_END
