#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomizePanel_HasMyRoom

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomizePanel_HasMyRoom.WBP_CustomizePanel_HasMyRoom_C
// 0x0020 (0x03A8 - 0x0388)
class UWBP_CustomizePanel_HasMyRoom_C final : public UCustomizePanelMyRoomWidget
{
public:
	class UWidgetAnimation*                       Ani_loopEnd;                                       // 0x0388(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_loop;                                          // 0x0390(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 backImage_gradation_top;                           // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 backImage_gradation_under;                         // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomizePanel_HasMyRoom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomizePanel_HasMyRoom_C")
	}
	static class UWBP_CustomizePanel_HasMyRoom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomizePanel_HasMyRoom_C>();
	}
};

SDK_NAMESPACE_END
