#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RecommendGuildRequeset

#include "Basic.hpp"

#include "WBP_RecommendGuildRequeset_classes.hpp"
#include "WBP_RecommendGuildRequeset_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_RecommendGuildRequeset.WBP_RecommendGuildRequeset_C.ExecuteUbergraph_WBP_RecommendGuildRequeset
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecommendGuildRequeset_C::ExecuteUbergraph_WBP_RecommendGuildRequeset(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecommendGuildRequeset_C", "ExecuteUbergraph_WBP_RecommendGuildRequeset");

	Params::WBP_RecommendGuildRequeset_C_ExecuteUbergraph_WBP_RecommendGuildRequeset Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecommendGuildRequeset.WBP_RecommendGuildRequeset_C.BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    leftButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_RecommendGuildRequeset_C::BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType, bool leftButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecommendGuildRequeset_C", "BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature");

	Params::WBP_RecommendGuildRequeset_C_BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;
	Parms.leftButton = leftButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecommendGuildRequeset.WBP_RecommendGuildRequeset_C.BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RecommendGuildRequeset_C::BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecommendGuildRequeset_C", "BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature");

	Params::WBP_RecommendGuildRequeset_C_BndEvt__WBP_RecommendGuildRequeset__popupWindow_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RecommendGuildRequeset.WBP_RecommendGuildRequeset_C.OnInviteCompleted
// (Event, Protected, BlueprintEvent)

void UWBP_RecommendGuildRequeset_C::OnInviteCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RecommendGuildRequeset_C", "OnInviteCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
