#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LoginBonusPopupDaily

#include "Basic.hpp"

#include "WBP_LoginBonusPopupDaily_classes.hpp"
#include "WBP_LoginBonusPopupDaily_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_LoginBonusPopupDaily.WBP_LoginBonusPopupDaily_C.ExecuteUbergraph_WBP_LoginBonusPopupDaily
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_LoginBonusPopupDaily_C::ExecuteUbergraph_WBP_LoginBonusPopupDaily(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_LoginBonusPopupDaily_C", "ExecuteUbergraph_WBP_LoginBonusPopupDaily");

	Params::WBP_LoginBonusPopupDaily_C_ExecuteUbergraph_WBP_LoginBonusPopupDaily Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_LoginBonusPopupDaily.WBP_LoginBonusPopupDaily_C.BndEvt__WBP_LoginBonus_Daily__tokushoButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UAppWidget*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EWidgetInputType                        inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_LoginBonusPopupDaily_C::BndEvt__WBP_LoginBonus_Daily__tokushoButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_LoginBonusPopupDaily_C", "BndEvt__WBP_LoginBonus_Daily__tokushoButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature");

	Params::WBP_LoginBonusPopupDaily_C_BndEvt__WBP_LoginBonus_Daily__tokushoButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_LoginBonusPopupDaily.WBP_LoginBonusPopupDaily_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_LoginBonusPopupDaily_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_LoginBonusPopupDaily_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
