#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TrainingWarning

#include "Basic.hpp"

#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TrainingWarning.WBP_TrainingWarning_C
// 0x0008 (0x0378 - 0x0370)
class UWBP_TrainingWarning_C final : public UWidgetBase
{
public:
	class UImage*                                 Image_421;                                         // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TrainingWarning_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TrainingWarning_C")
	}
	static class UWBP_TrainingWarning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TrainingWarning_C>();
	}
};

SDK_NAMESPACE_END
