#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayMenu_MyADButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PlayMenu_MyADButton.WBP_PlayMenu_MyADButton_C
// 0x0008 (0x0520 - 0x0518)
class UWBP_PlayMenu_MyADButton_C final : public UPlayMenuMyADButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0518(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnInitialized();
	void ExecuteUbergraph_WBP_PlayMenu_MyADButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayMenu_MyADButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayMenu_MyADButton_C")
	}
	static class UWBP_PlayMenu_MyADButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayMenu_MyADButton_C>();
	}
};

SDK_NAMESPACE_END
