#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BattleRuleChoiceButton

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BattleRuleChoiceButton.WBP_BattleRuleChoiceButton_C
// 0x0008 (0x0528 - 0x0520)
class UWBP_BattleRuleChoiceButton_C final : public UBattleRuleChoiceButtonWidget
{
public:
	class UNamedSlot*                             Body;                                              // 0x0520(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BattleRuleChoiceButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BattleRuleChoiceButton_C")
	}
	static class UWBP_BattleRuleChoiceButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BattleRuleChoiceButton_C>();
	}
};

SDK_NAMESPACE_END
