#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TabHeaderEdgeBG

#include "Basic.hpp"

#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TabHeaderEdgeBG.WBP_TabHeaderEdgeBG_C
// 0x0000 (0x0370 - 0x0370)
class UWBP_TabHeaderEdgeBG_C final : public UWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TabHeaderEdgeBG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TabHeaderEdgeBG_C")
	}
	static class UWBP_TabHeaderEdgeBG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TabHeaderEdgeBG_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TabHeaderEdgeBG_C;

SDK_NAMESPACE_END
