#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomMatchTenkey

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UIFramework_structs.hpp"
#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomMatchTenkey.WBP_CustomMatchTenkey_C
// 0x0030 (0x03A0 - 0x0370)
class UWBP_CustomMatchTenkey_C final : public UWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_EmptyWindow_C*                     WBP_EmptyWindow;                                   // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ReturnButton_C*                    WBP_ReturnButton;                                  // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_TenKey_C*                          WBP_TenKey;                                        // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(const class FString& ID)> DecideId;                                // 0x0390(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_WBP_CustomMatchTenkey(int32 EntryPoint);
	void BndEvt__WBP_CustomMatchTenkey_WBP_EmptyWindow_K2Node_ComponentBoundEvent_3_OnOutsideButtonDownEventDelegate__DelegateSignature();
	void BndEvt__WBP_CustomMatchTenkey_WBP_EmptyWindow_K2Node_ComponentBoundEvent_2_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_CustomMatchTenkey_WBP_TenKey_K2Node_ComponentBoundEvent_1_DecideIdDelegate__DelegateSignature(const class FString& Number);
	void BndEvt__WBP_CustomMatchTenkey_WBP_ReturnButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void Open();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomMatchTenkey_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomMatchTenkey_C")
	}
	static class UWBP_CustomMatchTenkey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomMatchTenkey_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CustomMatchTenkey_C;

SDK_NAMESPACE_END
