#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LicensePurchaseWindow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "OutGameModule_structs.hpp"
#include "OutGameModule_classes.hpp"
#include "UIFramework_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_LicensePurchaseWindow.WBP_LicensePurchaseWindow_C
// 0x0058 (0x0420 - 0x03C8)
class UWBP_LicensePurchaseWindow_C final : public USeasonPassLicensePurchaseWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_LicenseCautionWindow_C*            _expPurchasePopup;                                 // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_GeneralWindow_C*                   _purchasePopup;                                    // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class USeasonPassListObject*>          _stockList;                                        // 0x03E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	ELicencePurchaseType                          purchaseLicenceType;                               // 0x03F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F1[0x7];                                      // 0x03F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              StartTime;                                         // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          _LevelCloseFlag;                                   // 0x0400(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_401[0x7];                                      // 0x0401(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              closeAllLevel;                                     // 0x0408(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          _needUpdate;                                       // 0x0418(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          _LevelMoveFlag;                                    // 0x0419(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_WBP_LicensePurchaseWindow(int32 EntryPoint);
	void ButtonClosedDelegate();
	void PurchaseMiddleLicenseCompleteEvent(int32 requestId);
	void CustomEvent_4(int32 requestId);
	void CustomEvent_3();
	void CustomEvent_2();
	void Construct();
	void CustomEvent_1(class UAppWidget* Widget, EWidgetInputType inputType);
	void CustomEvent(class UAppWidget* Widget, EWidgetInputType inputType);
	void PurchasespecialLicenseComplete(int32 requestId);
	void OnBuyItemDispatcher_イベント_0();
	void BndEvt__WBP_LicensePurchaseWindow__expPurchasePopup_K2Node_ComponentBoundEvent_10_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_LicensePurchaseWindow__purchasePopup_K2Node_ComponentBoundEvent_9_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_7_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_LicensePurchaseWindow__purchasePopup_K2Node_ComponentBoundEvent_5_OnWindowInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType, bool leftButton);
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_2_OnWindowInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType, bool leftButton);
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_8_AddItemDelegate__DelegateSignature(const int32 value);
	void OnDecideDelegate_イベント_2(class UAppWidget* Widget, EWidgetInputType inputType);
	void ExpPurchasePopupOnDecideDelegate(class UAppWidget* Widget, EWidgetInputType inputType);
	void _itemAddEvent_イベント_0(const int32 value);
	void PurchaseProLicenseCompleteEvent(int32 requestId);
	void BndEvt__WBP_LicensePurchaseWindow__purchasePopup_K2Node_ComponentBoundEvent_4_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_0_OnWindowEventDelegate__DelegateSignature();
	void OnDecideDelegate_イベント_1(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_3_OnWindowEventDelegate__DelegateSignature();
	void BndEvt__WBP_LicensePurchaseWindow_WBP_GeneralShoppingWindow_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void WindowOpen(ELicencePurchaseType NewParam);
	void WindowClose();
	void Request_Complete(int32 RequestID_A, int32 RequestID_B, bool* Result);
	void UpdateCurrency();
	void SetButtonActive(bool IsActive);
	void SetPurchaseItem();
	void SetUpWindowText();
	void SetUpItemGet();
	void UpdateStock(int32* stockNumber);
	void WindowOpenPurchasePopUp();
	void UpdateLicense();
	void CheckBuyItemEnough();
	void SetStartTime();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LicensePurchaseWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LicensePurchaseWindow_C")
	}
	static class UWBP_LicensePurchaseWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LicensePurchaseWindow_C>();
	}
};

SDK_NAMESPACE_END
