#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CustomAdjustText

#include "Basic.hpp"

#include "GameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CustomAdjustText.WBP_CustomAdjustText_C
// 0x0000 (0x0688 - 0x0688)
class UWBP_CustomAdjustText_C final : public UCustomAdjustText
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CustomAdjustText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CustomAdjustText_C")
	}
	static class UWBP_CustomAdjustText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CustomAdjustText_C>();
	}
};

SDK_NAMESPACE_END
