#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LicenseCautionWindow

#include "Basic.hpp"

#include "UIFramework_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_LicenseCautionWindow.WBP_LicenseCautionWindow_C
// 0x0008 (0x0378 - 0x0370)
class UWBP_LicenseCautionWindow_C final : public UWidgetBase
{
public:
	class UWBP_GeneralWindowFrame_C*              WBP_GeneralWindowFrame;                            // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Open();
	void Close();
	void GetRightButton(class UWidgetButton** rightButton);
	void GetLeftButton(class UWidgetButton** leftButton);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LicenseCautionWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LicenseCautionWindow_C")
	}
	static class UWBP_LicenseCautionWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LicenseCautionWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_LicenseCautionWindow_C;

SDK_NAMESPACE_END
