#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TermsOfService_Top

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_TermsOfService_Top.WBP_TermsOfService_Top_C
// 0x0000 (0x0390 - 0x0390)
class UWBP_TermsOfService_Top_C final : public UTermsOfServiceWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TermsOfService_Top_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TermsOfService_Top_C")
	}
	static class UWBP_TermsOfService_Top_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TermsOfService_Top_C>();
	}
};

SDK_NAMESPACE_END
