#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FriendList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FriendList.WBP_FriendList_C
// 0x0008 (0x0420 - 0x0418)
class UWBP_FriendList_C final : public UFriendListWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_FriendList(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FriendList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FriendList_C")
	}
	static class UWBP_FriendList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FriendList_C>();
	}
};

SDK_NAMESPACE_END
