#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NoticeExplanationTimer

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NoticeExplanationTimer.WBP_NoticeExplanationTimer_C
// 0x0010 (0x03A8 - 0x0398)
class UWBP_NoticeExplanationTimer_C final : public UNoticeExplanationTimer
{
public:
	class UImage*                                 _bkImage;                                          // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_76;                                          // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NoticeExplanationTimer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NoticeExplanationTimer_C")
	}
	static class UWBP_NoticeExplanationTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NoticeExplanationTimer_C>();
	}
};

SDK_NAMESPACE_END
