#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayMenuDebugListEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OutGameModule_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "UIFramework_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PlayMenuDebugListEntry.WBP_PlayMenuDebugListEntry_C
// 0x0040 (0x0420 - 0x03E0)
class UWBP_PlayMenuDebugListEntry_C final : public UPlayMenuDebugListEntryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_PlayMenuHamburgerMenu_C*           Pearent;                                           // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMenuHamburgerDebugListEntryObject* As_Play_Menu_Hamburger_Debug_List_Entry_Object;    // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UWBP_PlayMenu_C*                        PlayMenu;                                          // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           FocusColor;                                        // 0x0400(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           NotFocusColor;                                     // 0x0410(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PlayMenuDebugListEntry(int32 EntryPoint);
	void BndEvt__WBP_PlayMenuDebugListEntry__debugListButton_K2Node_ComponentBoundEvent_2_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BndEvt__WBP_PlayMenuDebugListEntry__debugListButton_K2Node_ComponentBoundEvent_0_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void Construct();
	void BndEvt__WBP_WindowButton_K2Node_ComponentBoundEvent_1_OnInputEventDelegate__DelegateSignature(class UAppWidget* Widget, EWidgetInputType inputType);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void RunDebugType();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayMenuDebugListEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayMenuDebugListEntry_C")
	}
	static class UWBP_PlayMenuDebugListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayMenuDebugListEntry_C>();
	}
};

SDK_NAMESPACE_END
