#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemIconNamePlateBG

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ItemIconNamePlateBG.WBP_ItemIconNamePlateBG_C
// 0x0000 (0x0378 - 0x0378)
class UWBP_ItemIconNamePlateBG_C final : public UItemIconNamePlateBGWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ItemIconNamePlateBG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ItemIconNamePlateBG_C")
	}
	static class UWBP_ItemIconNamePlateBG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ItemIconNamePlateBG_C>();
	}
};

SDK_NAMESPACE_END
