#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EventRankEntry

#include "Basic.hpp"

#include "OutGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_EventRankEntry.WBP_EventRankEntry_C
// 0x0000 (0x03A0 - 0x03A0)
class UWBP_EventRankEntry_C final : public UEventRankEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EventRankEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EventRankEntry_C")
	}
	static class UWBP_EventRankEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EventRankEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EventRankEntry_C;

SDK_NAMESPACE_END
