#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonEntryBG

#include "Basic.hpp"

#include "WBP_SeasonEntryBG_classes.hpp"
#include "WBP_SeasonEntryBG_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.ExecuteUbergraph_WBP_SeasonEntryBG
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonEntryBG_C::ExecuteUbergraph_WBP_SeasonEntryBG(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "ExecuteUbergraph_WBP_SeasonEntryBG");

	Params::WBP_SeasonEntryBG_C_ExecuteUbergraph_WBP_SeasonEntryBG Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_SeasonEntryBG_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SeasonEntryBG_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "PreConstruct");

	Params::WBP_SeasonEntryBG_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonEntryBG_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "OnListItemObjectSet");

	Params::WBP_SeasonEntryBG_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SeasonEntryBG_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "BP_OnItemSelectionChanged");

	Params::WBP_SeasonEntryBG_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SeasonEntryBG_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "BP_OnItemExpansionChanged");

	Params::WBP_SeasonEntryBG_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEntryBG.WBP_SeasonEntryBG_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_SeasonEntryBG_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEntryBG_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
