#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SupplyRequest

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SupplyRequest.WBP_SupplyRequest_C
// 0x0008 (0x0450 - 0x0448)
class UWBP_SupplyRequest_C final : public UUMGSupplyRequest
{
public:
	class UImage*                                 Image_78;                                          // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SupplyRequest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SupplyRequest_C")
	}
	static class UWBP_SupplyRequest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SupplyRequest_C>();
	}
};

SDK_NAMESPACE_END
