#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ShopPickup

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ShopPickup.WBP_ShopPickup_C.ExecuteUbergraph_WBP_ShopPickup
// 0x0020 (0x0020 - 0x0000)
struct WBP_ShopPickup_C_ExecuteUbergraph_WBP_ShopPickup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_inText;                               // 0x0008(0x0018)(ConstParm)
};

// Function WBP_ShopPickup.WBP_ShopPickup_C.SetShopItemName
// 0x0018 (0x0018 - 0x0000)
struct WBP_ShopPickup_C_SetShopItemName final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
